names:
- car
- person
- traffic_light_red
- traffic_light_green
- traffic_light_yellow
nc: 5
roboflow:
  license: CC BY 4.0
  project: traffic-lights-qh0vp
  url: https://universe.roboflow.com/version-ou-je-vais-merge/traffic-lights-qh0vp/dataset/1
  version: 1
  workspace: version-ou-je-vais-merge
test: ../test/images
train: D:\Work\Atomcamp\Final Project\Dataset_trafficlights\..\train\images
val: D:\Work\Atomcamp\Final Project\Dataset_trafficlights\..\valid\images
